/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Help.java
 *
 * Created on 21-Oct-2011, 23:11:44
 */
package itag;

/**
 *
 * @author s0789266
 */
public class Help extends javax.swing.JFrame {

    /** Creates new form Help */
    public Help() {
        initComponents();
        setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("<html>\n<p><b>Help with iTag:</b></p>\n<p> </p>\n<p><b>Opening an image to tag:</b></p>\n<p>- Click \"File\"</p>\n<p>- Click \"Open\"</p>\n<p><i>(If you already have an image open, you will be prompted to save its tags.)</i></p>\n<p> </p>\n<p><b>Tagging an image:</b></p>\n<p>- Start clicking on the image in the panel highlighting the countours of the tag</p>\n<p> </p>\n<p><b>Finishing a tag:</b></p>\n<p>- Once you're finished with the tag, click \"Finish Tag\"</p>\n<p><i>(The first and last points of the tag will be joined so make sure you've highlighted the countour of your tag correctly!)</i></p>\n<p> </p>\n<p><b>Saving image tags:</b></p>\n<p>- Click \"File\"</p>\n<p>- Click \"Save\"</p>\n<p><i>(Tags will be saved for next time you open this image.)</i></p>\n<p> </p>\n<p><b>Renaming a tag:</b></p>\n<p>- Highlight the tag in the \"Tag List\"</p>\n<p>- Click \"Rename Tag\"</p>\n<p> </p>\n<p><b>Deleting a tag:</b></p>\n<p>- Highlight the tag in the \"Tag List\"</p>\n<p>- Click \"Delete Tag\"</p>\n<p> </p>\n<p><b>Undoing a point:</b></p>\n<p>- Click \"Undo Point\" before you finish the tag</p>\n<p></p>\n<p><b>Changing a tag's colour:</b></p>\n<p>- Click the \"Tag Color\" drop down box and select your colour\n<p></p>\n<p><b>Closing the image:</b></p>\n<p>- Click \"File\"</p>\n<p>- Click \"Close\"</p>\n<p><i>(If you have an image open, you will be prompted to save its tags.)</i></p>\n<p></p>\n<p><b>Exiting the program:</b></p>\n<p>- Click \"File\"</p>\n<p>- Click \"Exit\"</p>\n<p><i>(If you have an image open, you will be prompted to save its tags.)</i></p>\n\n</html>");
        jLabel1.setPreferredSize(new java.awt.Dimension(442, 442));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void okActionPerformed(java.awt.event.ActionEvent evt) {
        setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Help().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
